### PR TITLE
Zulu OpenJDK

### PR DESCRIPTION
**Pull request by WGOS**
1. Changed from OpenJDK to Zulu OpenJDK so that decreases amount of consumed RAM by 10-20% and loading speeds are faster by ~15%
2. Changed to Alpine Linux due to lightweight

### CODE REVIEW

**Comment by parkervcp** [comment]
This could affect more than just the single server you ran. This is no from me.

Other servers could fail horribly with this.

**Comment by DaneEveritt** [comment]
I'm with @parkervcp here, but wouldn't be opposed to it being a new image that we host.

**Comment by WGOS** [comment]
> This could affect more than just the single server you ran. This is no from me.
> 
> Other servers could fail horribly with this.

Well, it worked fine for me for years.


> I'm with @parkervcp here, but wouldn't be opposed to it being a new image that we host.

Yes, it's probably should be a new image
Actually I uploaded it to Docker hub already `wgos/pteroq-images:java-zulu` so it could be tested

**Comment by parkervcp** [comment]
We have a Java open j9 image. So I don't see why we wouldn't add another jvm image.

**Comment by WGOS** [comment]
It could be just another alternative option, I think.
Are there compatibility issues with Alpine? Just interesting

**Comment by parkervcp** [comment]
Alpine uses muslc and not glibc. This has caused issues with modded servers in the past. Before moving to debian we were running alpine-java-glibc but it used oracle java and got dcma'd.

**Comment by parkervcp** [comment]
Well that was gross and I am sorry I made all that noise there adding and changing the branch.

**Comment by WGOS** [comment]
Uh, that wasn't gross at all. Just a regular discussion

**Comment by parkervcp** [comment]
I was talking about all the changes and the merge conflict I added by changing the base branch.

**Comment by WGOS** [comment]
I also unmentioned that Forge does not work on OpenJ9 properly. In my case it freezes with Sponge and server doesn't launch

**Comment by parkervcp** [comment]
There is a reason openj9 isn't default...

**Comment by WGOS** [comment]
I finally resolved all problems with git so it may be ready to merge, I suppose

**Comment by WGOS** [comment]
As I see on Zulu in Alpine docker uses glibc (it's event stated on their site that glibc required). So maybe redo this container on Alpine due lightweight?

**Pull request merged**
