### PR TITLE
removing rcon.port form env

### PR DESCRIPTION
**Pull request by fabri2000779**
Detect the rcon port from the startup command

### CODE REVIEW

**Comment by parkervcp** [comment]
This was fine and used the rcon environment variable just like the startup does.

**Comment by fabri2000779** [comment]
is just a suggestion, i consider this useful in our case worked to automate the rcon assignment via WHMCS since you cant really change env variables throught the API without do API modifications, i may be wrong

**Comment by fabri2000779** [comment]
feel free to close this PR if you think this isnt needed :)

**Comment by parkervcp** [comment]
It should work via whmcs if you set the variable value.

**Comment by fabri2000779** [comment]
i was talking about our usecase but i see is not really needed here. Sorry for the inconvenience.

**Pull request closed without merging**
