### PR TITLE
Neosvr beta headless client / server image

### PR DESCRIPTION
**Pull request by Synkstar**
To solve issues with this pull request https://github.com/parkervcp/eggs/pull/1173.

Kind of expected that they wouldn't let someone put a docker image they don't control in an egg for security reasons.

### CODE REVIEW

**Comment by parkervcp** [comment]
pr images to my image repo homie...

**Comment by parkervcp** [comment]
I also already have a mono image.

**Comment by Synkstar** [comment]
The core mono image crashes for some reason when I try to use it

**Comment by Synkstar** [comment]
> pr images to my image repo homie...

Moved to https://github.com/parkervcp/images/pull/90

**Comment by rose-is-gay** [comment]
meow

**Pull request closed without merging**
